### ISSUE TITLE
Trigger from background

### ISSUE THREAD

**Issue by FilipKvestak** [EddieKamau/flutter_overlay_apps#7]
Hi, 
how do you trigger it while the app is working in background?

I would like to raise this overlay widget while app is working in background. My trigger is Firebase Messaging Service that is working in the background and listens on new messages (notifications). 

It breaks when calling it from background.
Funny thing is, I can call it with delay from foreground, while I have an app context. I only use Future.delayed() and put the app in background and after a minute or 2 the overlay displays successfully. But I cant't get it to work by triggering it while app is in background. 

`E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): Failed to handle method call
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): kotlin.UninitializedPropertyAccessException: lateinit property activity has not been initialized
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at com.phan_tech.flutter_overlay_apps.FlutterOverlayAppsPlugin.onMethodCall(FlutterOverlayAppsPlugin.kt:92)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#com.phan_tech./flutter_overlay_apps(12826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (12826): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property activity has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property activity has not been initialized
E/flutter (12826): 	at com.phan_tech.flutter_overlay_apps.FlutterOverlayAppsPlugin.onMethodCall(FlutterOverlayAppsPlugin.kt:92)
E/flutter (12826): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (12826): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (12826): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (12826): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (12826): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (12826): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (12826): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (12826): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (12826): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/flutter (12826): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12826): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (12826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (12826): )
E/flutter (12826): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (12826): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (12826): <asynchronous suspension>
E/flutter (12826): #2      FlutterOverlayApps.showOverlay (package:flutter_overlay_apps/flutter_overlay_apps.dart:31:24)
E/flutter (12826): <asynchronous suspension>
E/flutter (12826): #3      OverlayService.sendOverlay (package:cbc_alert/app/services/overlay_service.dart:13:5)
E/flutter (12826): <asynchronous suspension>
E/flutter (12826): `

**Comment by abr13** [comment]
any solution? or workaround to achieve this behavior?

**Comment by HeyRonak** [comment]
Any update on this

**Comment by boyd-boyd** [comment]
@HeyRonak  @abr13  @FilipKvestak  do you guys found any workaround of invoking it from background? or any alternate solution.

**Comment by adrianbus** [comment]
Anything new about this issue?

**Comment by abr13** [comment]
@boyd-boyd You can try https://pub.dev/packages/flutter_overlay_window it worked for me from background notification.

**Comment by saurabhkumar8112** [comment]
The best way would be to run this overlay service in a separate flutterEngine(and a separate isolate). From there you can call this service in the background and it will work. 
[Flutter Overlay Window](https://pub.dev/packages/flutter_overlay_window) does precisely that, you can checkout the native code.
Or you can simply incorporate the workaround i mentioned above

**Comment by taghassan54** [comment]
@abr13 i'm facing same issue in [flutter_overlay_window](https://pub.dev/packages/flutter_overlay_window) it's not working if app is closed 

```
Fatal Exception: java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: java.lang.NullPointerException: Attempt to invoke virtual method 'wd.a io.flutter.embedding.engine.a.j()' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4627)
       at android.app.ActivityThread.access$1600(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
